Tools/BuildOurOwnBabylonJS/BuildOurOwnBabylonJSServer/Controllers/BabylonJSDemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuildOurOwnBabylonJSServer.Controllers
{
    public class BabylonJSDemoController : Controller
    {
        public ActionResult Index(string demoFolderName, string demoFile)
        {
            ViewBag.DemoFolderName = demoFolderName;
            ViewBag.DemoFile = demoFile;
            
            return View();
        }
    }
}

Tools/BuildOurOwnBabylonJS/BuildOurOwnBabylonJSServer/Controllers/BuildOurOwnBabylonJSController.cs
using System.Web.Mvc;
using System.IO;
using System.Text;
using System;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;

namespace BuildOurOwnBabylonJSServer.Controllers
{
    public class BuildOurOwnBabylonJSController : Controller
    {
        public const string GetFileContentActionName = "GetFileContent";
        public const string GetBabylonScenesActionName = "GetBabylonScenes";
        
        [ActionName(BuildOurOwnBabylonJSController.GetFileContentActionName)]
        public ActionResult GetFileContent(string rootPath, string relPath)
        {
            try
            {
                var babylonJSPath = Path.Combine(Server.MapPath("~"), rootPath);

                var absPath = Path.Combine(babylonJSPath, relPath);

                var type = "";
                var extension = "";

                if (!String.IsNullOrEmpty(relPath))
                    extension = Path.GetExtension(relPath).ToLower();

                switch (extension)
                {
                    case ".js":
                    case ".babylon":
                    case ".manifest":
                        type = "text/javascript";
                        break;

                    case ".png":
                        type = "image/png";
                        break;

                    case ".jpeg":
                    case ".jpg":
                        type = "image/jpeg";
                        break;

                    case ".bmp":
                        type = "image/bmp";
                        break;

                    case ".css":
                        type = "text/css";
                        break;

                    default:
                        type = "text/plain";
                        break;
                }
            
                return File(new FileStream(absPath, FileMode.Open), type);
            }
            catch
            {
                return new HttpNotFoundResult();
            }
        }

        [ActionName(BuildOurOwnBabylonJSController.GetBabylonScenesActionName)]
        public string GetBabylonScenes(string rootPath)
        {
            try
            {
                var dir = new DirectoryInfo(rootPath);
                var subDirs = dir.GetDirectories();
                var files = new List<JObject>();

                foreach (var directory in subDirs)
                {
                    var babylonFiles = directory.GetFiles("*.babylon");

                    if (babylonFiles.Length == 0)
                        continue;

                    foreach (var file in babylonFiles)
                    {
                        var linkName = directory.Name + "/" + Path.GetFileNameWithoutExtension(file.Name);
                        files.Add(new JObject(
                            new JProperty("url", Url.Action("Index", "BabylonJSDemo", new { demoFolderName = directory.Name, demoFile = file.Name })),
                            new JProperty("linkName", linkName)
                        ));
                    }
                }

                var json = new JObject(new JProperty("files", files));
                return json.ToString(Newtonsoft.Json.Formatting.None);
            }
            catch
            {
                var json = new JObject(new JProperty("files", ""));
                return json.ToString(Newtonsoft.Json.Formatting.None);
            }
        }
    }
}

Tools/BuildOurOwnBabylonJS/BuildOurOwnBabylonJSServer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuildOurOwnBabylonJSServer.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Tools/BuildOurOwnBabylonJS/BuildOurOwnBabylonJSServer/Controllers/OurDemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using BuildOurOwnBabylonJSServer.ViewModels;

namespace BuildOurOwnBabylonJSServer.Controllers
{
    public class OurDemoController : Controller
    {
        public ActionResult Show(string viewName, 
            string folder = "")
        {
            var form = Request.Form;
            var queryString = Request.QueryString;
            var dictionary = new Dictionary<string, string>(form.Count + queryString.Count);

            var keys = form.AllKeys;
            
            foreach(var k in keys)
            {
                if (k == "viewName" || k == "folder")
                    continue;
                dictionary.Add(k, form.GetValues(k).First());
            }

            keys = queryString.AllKeys;

            foreach (var k in keys)
            {
                if (k == "viewName" || k == "folder")
                    continue;
                dictionary.Add(k, queryString.GetValues(k).First());
            }

            return View(Path.Combine(folder, viewName),
                new OurDemoViewModel { Folder = folder, Dictionary = dictionary });
        }
    }
}

Tools/BuildOurOwnBabylonJS/BuildOurOwnBabylonJSServer/Controllers/SandBoxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BuildOurOwnBabylonJSServer.Controllers
{
    public class SandBoxController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Tools/BuildOurOwnBabylonJS/BuildOurOwnBabylonJSServer/Views/BabylonJSDemo/Index.cshtml
@using BuildOurOwnBabylonJSServer.Extensions;
@{
    ViewBag.Title = "Our Own BabylonJS";
    ViewBag.BabylonJSFolder = "..\\..\\..\\";
}

<script type="text/javascript">
    $(document).ready(function () {

        var loading = new OURBABYLON.Loading(OURBABYLON.canvas.parentElement);

        loading.show();

        BABYLON.SceneLoader.Load("@Html.Raw(this.BabylonJSSamplesFile("Scenes/" + (string)ViewBag.DemoFolderName))" + "@Url.Encode("/")", "@ViewBag.DemoFile", OURBABYLON.engine, function (scene) {
            OURBABYLON.sceneInitialization(scene);
            scene.activeCamera.attachControl(OURBABYLON.canvas);

            // Render loop
            var renderLoop = function () {
                scene.render();
            };

            // Launch render loop
            scene.getEngine().runRenderLoop(renderLoop);

            loading.hide();

        }, $.proxy(loading.onProgress, loading));
    });
</script>

Tools/BuildOurOwnBabylonJS/BuildOurOwnBabylonJSServer/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Our Own BabylonJS";
    ViewBag.DoNotUseBabylonJS = true;
}

<div id="logo">
<img src="@Url.Content("/Content/Logo.png")" />
</div>

Tools/BuildOurOwnBabylonJS/BuildOurOwnBabylonJSServer/Views/OurDemo/sample.cshtml
@model OurDemoViewModel
@using BuildOurOwnBabylonJSServer.ViewModels
@using System.Text.RegularExpressions

@{
    ViewBag.Title = "Our Own BabylonJS";
    ViewBag.BabylonJSFolder = "..\\..\\..\\";

    var myRegex = new Regex(@"[\\]", RegexOptions.Singleline);

    Model.Folder = myRegex.Replace(Model.Folder, @"/");
    Model.Folder = Model.Folder.Trim('/');

    if (!String.IsNullOrEmpty(Model.Folder))
    {
        Model.Folder += "/";
    }
}

<script type="text/javascript">
    $(document).ready(function () {
        BABYLON.SceneLoader.Load("/Content/@Model.Folder", "@Model.Dictionary["fileBJS"]" + ".babylon", OURBABYLON.engine, function (scene) {

            scene.activeCamera = new BABYLON.ArcRotateCamera("defaultCamera", 0, 0, 100, BABYLON.Vector3.Zero(), scene);

            scene.activeCamera.zoomOn();
            scene.activeCamera.attachControl(OURBABYLON.canvas);

            var material = new BABYLON.StandardMaterial("default", scene);
            material.emissiveColor = new BABYLON.Color3(0.7, 0.7, 0.7);

            for (var m in scene.meshes) {
                scene.meshes[m].material = material;
            }

            // Render loop
            var renderLoop = function () {
                scene.render();
            };

            // Launch render loop
            scene.getEngine().runRenderLoop(renderLoop);

            OURBABYLON.currentScene = scene;
        });
    });
</script>

Tools/BuildOurOwnBabylonJS/BuildOurOwnBabylonJSServer/Views/SandBox/Index.cshtml
@{
    ViewBag.Title = "Our Own BabylonJS";
    ViewBag.BabylonJSFolder = "..\\..\\..\\";
}
<style>
    #loadingInfos {
        color: #888888;
        cursor: default;
        font-size: 30px;
        height: 60px;
        left: 0;
        margin-top: -30px;
        padding-top: 10px;
        position: absolute;
        text-align: center;
        bottom: 0;
        transition: transform 0.25s ease-in-out 0s;
        width: calc(100% - 10px);
        z-index: 3;
        border: 5px dotted gray;
        pointer-events: none;
    }

    #loadingInfos .content {
        position: relative;
        top: 50%;
    }

    .loadingInfos {
        transform: translateX(120%);
        -webkit-transform: translate(120%);
    }
</style>
<div id="loadingInfos"><div class="content">Drag and drop your .babylon files inside, with associated assets</div></div>

<script type="text/javascript">
    $(document).ready(function () {
        var loading = new OURBABYLON.Loading(OURBABYLON.canvas.parentElement);

        var loadingInfos = document.getElementById("loadingInfos");

        loadingInfos.style.height = (OURBABYLON.canvas.height-20)+"px";
        window.addEventListener('resize', function () {
            loadingInfos.style.height = (OURBABYLON.canvas.height - 20) + "px";
        });

        var filesInput = new BABYLON.FilesInput(OURBABYLON.engine, OURBABYLON.currentScene, OURBABYLON.canvas, function (sceneFile, babylonScene) {
            OURBABYLON.sceneInitialization(babylonScene, true);
            loading.hide();
        }, $.proxy(loading.onProgress, loading), null, null, function () {
            loading.show();
            loadingInfos.className = "loadingInfos";
        });
        filesInput.monitorElementForDragNDrop(OURBABYLON.canvas);
    });
</script>

Tools/BuildOurOwnBabylonJS/BuildOurOwnBabylonJSServer/Views/Shared/_Layout.cshtml
@using BuildOurOwnBabylonJSServer.Extensions;
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
    @if (ViewBag.DoNotUseBabylonJS == null)
    {
        @Html.Raw(this.BabylonJSStyle(@"Tools\BuildOurOwnBabylonJS\BuildOurOwnBabylonJSShared\Style\Loading.css"))
        @Html.Raw(this.BabylonJSScript("cannon.js"))
        @Html.Raw(this.BabylonJSScript(@"Tools\BuildOurOwnBabylonJS\BuildOurOwnBabylonJS\ourOwnBabylon.js"))
        @Html.Raw(this.BabylonJSScript(@"Tools\BuildOurOwnBabylonJS\BuildOurOwnBabylonJSShared\Scripts\Loading.js"))
        <script type="text/javascript">
            var OURBABYLON = OURBABYLON || {};
            $(document).ready(function(){
                if (!BABYLON.Engine.isSupported()) {
                    alert("Your browser does not support WebGL so you can't use BabylonJS on it");
                    return;
                }

                OURBABYLON.canvas = document.getElementById("ourOwnBabylonJSCanvas");
                OURBABYLON.engine = new BABYLON.Engine(OURBABYLON.canvas, true);

                OURBABYLON.sceneInitialization = function (scene, attachControlToCamera) {
                    OURBABYLON.currentScene = scene;
                    if (!OURBABYLON.currentScene.activeCamera) {
                        OURBABYLON.currentScene.activeCamera = new BABYLON.ArcRotateCamera("DefaultCamera", Math.PI / 2, 0, 10, new BABYLON.Vector3.Zero(), OURBABYLON.currentScene);
                        OURBABYLON.currentScene.activeCamera.zoomOn();
                        if (attachControlToCamera) {
                            OURBABYLON.currentScene.activeCamera.attachControl(OURBABYLON.canvas);
                        }
                    }
                    if (OURBABYLON.currentScene.lights.length == 0) {
                        var light = new BABYLON.HemisphericLight("Default light", new BABYLON.Vector3(0, 1, 0), OURBABYLON.currentScene);
                    }
                };
                window.addEventListener("resize", function () {
                    OURBABYLON.engine.resize();
                });

                window.OURBABYLON = OURBABYLON;
            });
        </script>
    }
</head>
<body>
    <div id="main">
        <div id="title">
            <h1>@ViewBag.Title</h1>
            <div id="menu">
                <a href="@Url.Action("Index", "SandBox")">Sandbox</a>
            </div>
        </div>
        @if (ViewBag.DoNotUseBabylonJS == null)
        {
        <canvas id="ourOwnBabylonJSCanvas"></canvas>
        }
        @RenderBody()
        <script type="text/javascript">
            var menu = document.getElementById("menu");

            var req = new XMLHttpRequest();
            req.open('GET', "@Html.Raw(this.BabylonJSSamplesFolder())");
            req.onreadystatechange = function (evt) {
                if (req.readyState == 4) {
                    if (req.status == 200) {
                        var json = JSON.parse(req.responseText);
                        for (var i in json.files) {
                            var span = document.createElement("span");
                            span.innerHTML = " | ";
                            menu.appendChild(span);

                            var file = json.files[i];
                            var a = document.createElement("a");
                            a.setAttribute("href", file.url);
                            a.textContent = file.linkName.charAt(0).toUpperCase() + file.linkName.slice(1);
                            menu.appendChild(a);
                        }
                    }
                }
            };
            req.send(null);
        </script>
    </div>
</body>
</html>